export const TRIP_SHARE_TOKEN_BYTES = 48;
export const TRIP_SHARE_MAX_ITEMS = 200;
export const TRIP_SHARE_RATE_WINDOW_SECONDS = 60;
export const TRIP_SHARE_TOKEN_REQUESTS_PER_WINDOW = 30;
export const TRIP_SHARE_IP_REQUESTS_PER_WINDOW = 90;
