export const AUDIT_ACTIONS = {
  ADMIN_USER_SUSPENDED: 'ADMIN_USER_SUSPENDED',
  ADMIN_USER_RESTORED: 'ADMIN_USER_RESTORED',
  ADMIN_BUSINESS_SUSPENDED: 'ADMIN_BUSINESS_SUSPENDED',
  ADMIN_BUSINESS_RESTORED: 'ADMIN_BUSINESS_RESTORED',
  ADMIN_BUSINESS_STATUS_CHANGED: 'ADMIN_BUSINESS_STATUS_CHANGED',
  ADMIN_VERIFICATION_APPROVED: 'ADMIN_VERIFICATION_APPROVED',
  ADMIN_VERIFICATION_REJECTED: 'ADMIN_VERIFICATION_REJECTED',
} as const;

export const AUDIT_ENTITY_TYPES = {
  USER: 'USER',
  BUSINESS: 'BUSINESS',
  BUSINESS_VERIFICATION: 'BUSINESS_VERIFICATION',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
export type AuditEntityType =
  (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];
