export const AUDIT_ACTIONS = {
  ADMIN_USER_SUSPENDED: 'ADMIN_USER_SUSPENDED',
  ADMIN_USER_RESTORED: 'ADMIN_USER_RESTORED',
  ADMIN_BUSINESS_SUSPENDED: 'ADMIN_BUSINESS_SUSPENDED',
  ADMIN_BUSINESS_RESTORED: 'ADMIN_BUSINESS_RESTORED',
  ADMIN_BUSINESS_STATUS_CHANGED: 'ADMIN_BUSINESS_STATUS_CHANGED',
  ADMIN_VERIFICATION_APPROVED: 'ADMIN_VERIFICATION_APPROVED',
  ADMIN_VERIFICATION_REJECTED: 'ADMIN_VERIFICATION_REJECTED',
  ADMIN_DESTINATION_CREATED: 'ADMIN_DESTINATION_CREATED',
  ADMIN_DESTINATION_UPDATED: 'ADMIN_DESTINATION_UPDATED',
  ADMIN_DESTINATION_PUBLISHED: 'ADMIN_DESTINATION_PUBLISHED',
  ADMIN_DESTINATION_UNPUBLISHED: 'ADMIN_DESTINATION_UNPUBLISHED',
  ADMIN_BUSINESS_CATEGORY_CREATED: 'ADMIN_BUSINESS_CATEGORY_CREATED',
  ADMIN_BUSINESS_CATEGORY_UPDATED: 'ADMIN_BUSINESS_CATEGORY_UPDATED',
  ADMIN_SERVICE_CATEGORY_CREATED: 'ADMIN_SERVICE_CATEGORY_CREATED',
  ADMIN_SERVICE_CATEGORY_UPDATED: 'ADMIN_SERVICE_CATEGORY_UPDATED',
  ADMIN_REVIEW_PUBLISHED: 'ADMIN_REVIEW_PUBLISHED',
  ADMIN_REVIEW_REJECTED: 'ADMIN_REVIEW_REJECTED',
  ADMIN_REVIEW_HIDDEN: 'ADMIN_REVIEW_HIDDEN',
  ADMIN_REVIEW_RESTORED: 'ADMIN_REVIEW_RESTORED',
  ADMIN_REPORT_REVIEW_STARTED: 'ADMIN_REPORT_REVIEW_STARTED',
  ADMIN_REPORT_RESOLVED: 'ADMIN_REPORT_RESOLVED',
  ADMIN_REPORT_DISMISSED: 'ADMIN_REPORT_DISMISSED',
} as const;

export const AUDIT_ENTITY_TYPES = {
  USER: 'USER',
  BUSINESS: 'BUSINESS',
  BUSINESS_VERIFICATION: 'BUSINESS_VERIFICATION',
  DESTINATION: 'DESTINATION',
  BUSINESS_CATEGORY: 'BUSINESS_CATEGORY',
  SERVICE_CATEGORY: 'SERVICE_CATEGORY',
  REVIEW: 'REVIEW',
  REPORT: 'REPORT',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
export type AuditEntityType =
  (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];
